version: '3.8'

services:
  db:
    image: jameslaurino/mysql:latest
    container_name: mysql_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "first_db"
    ports:
      - "3306:3306"
  #    networks:
  #      - my_network
  #    volumes:
  #      - mysql_data_test:/var/lib/mysql

  backend:
    image: springback:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/first_db"
      SPRING_DATASOURCE_USERNAME : "root"
      SPRING_DATASOURCE_PASSWORD : "1234"
      SPRING_JPA_HIBERNATE_DDL_AUTO : "create-drop"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
    depends_on:
      - db

  frontend:
    image: nginxfront:latest
    container_name: nginx-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

#volumes:
#  mysql_data_test:

# const apiUrl = 'http://localhost:8080/api';