version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "fotova_db_dev"
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq_dev
    restart: always
    ports:
      - "5672:5672"  # Port pour les échanges AMQP
      - "15672:15672" # Port pour l'interface web RabbitMQ
    networks:
      - my_network

  mailHog:
    image: mailhog/mailhog
    container_name: mailhog_dev
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - my_network

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_dev
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_dev
    restart: always
    ports:
      - "11434:11434"
    networks:
      - my_network
    volumes:
      - ollama_data:/root/.ollama

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube_dev
    restart: always
    ports:
      - "9000:9000"
    networks:
      - my_network
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonarpass
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  nexus:
    image: sonatype/nexus3
    container_name: nexus_dev
    restart: always
    ports:
      - "8083:8081"
    networks:
      - my_network
    volumes:
      - nexus_data:/nexus-data

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
  ollama_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  nexus_data: