version: '3.8'

services:
  mysql:
    image: jameslaurino/mysql:latest
    container_name: mysql_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "first_db"
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq_dev
    restart: always
    ports:
      - "5672:5672"  # Port pour les échanges AMQP
      - "15672:15672" # Port pour l'interface web RabbitMQ
    networks:
      - my_network

  mailHog:
    image: mailhog/mailhog
    container_name: mailhog_dev
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - my_network

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
